### ISSUE TITLE
Makefile assumes $GOPATH is set

### ISSUE THREAD

**Issue by will-iov** [confio/weave#53]
go v1.8+ has a default value for `$GOPATH`, which should be respected in case the user has no $GOPATH set. Otherwise `make deps` fails at this point:

```
cd $GOPATH/src/github.com/tendermint/tendermint && \
		git checkout v0.17.1 && \
		make ensure_deps && make install && \
		git checkout -
/bin/sh: line 0: cd: /src/github.com/tendermint/tendermint: No such file or directory
make[1]: *** [/tendermint] Error 1
make: *** [deps] Error 2
```

https://beta.golang.org/doc/go1.8#gopath

**Comment by ethanfrey** [comment]
Thank you for this. I did not know this was updated (used to always setting GOPATH).

GOPATH defaults to $HOME/go in 4ca113d
