### ISSUE TITLE
go1.10.2: $GOPATH must not be set to $GOROOT

### ISSUE THREAD

**Issue by webmaster128** [confio/weave#65]
I followed [this instruction](https://weave.readthedocs.io/en/latest/mycoind/setup.html#install-go) to install go. However, this resulted in the following error

```
$ go get github.com/confio/weave
package github.com/confio/weave: cannot download, $GOPATH must not be set to $GOROOT. For more details see: 'go help gopath'
```

In this case $GOPATH was $HOME/go and $GOROOT was unset. Moving the installation to ~/go1.10.2 caused that go was not in PATH anymore.

I now have

```
export GOROOT="$HOME/go1.10.2"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOROOT/bin"
```

in by .bashrc, which seems to work. However, I am not an expert with Go, so I don't want to submit a documentation PR.

**Comment by ruseinov** [comment]
This really depends on your setup, in that manual that you've referred to there is no GOROOT defined and most of the time it is not needed either.

**Comment by webmaster128** [comment]
Okay, where do you install go when GOROOT is not defined?

**Comment by webmaster128** [comment]
/usr/local/go is it (as described in https://golang.org/doc/install#tarball).

My fault, sorry. Documentation is complete then.

**Comment by ruseinov** [comment]
@webmaster128 If you are on a mac - use homebrew to install go, there's no extra setup needed. I'm pretty sure linux would be the same if you bother to find a proper *.deb/*.rpm package.

**Comment by ruseinov** [comment]
@webmaster128 Go includes system takes a little bet to get used to, but once you do - it turns out to be so much easier than all the package-managers in the world.

**Comment by ruseinov** [comment]
Well, no extra setup excpet for GOPATH, of course. But that's your workspace.

**Comment by webmaster128** [comment]
Looks good: in current Ubuntu, there is go 1.10.x available (https://packages.ubuntu.com/bionic/golang) Thanks for the hint
