### ISSUE TITLE
go get github.com/confio/weave fails

### ISSUE THREAD

**Issue by webmaster128** [confio/weave#66]
Right now, `go get github.com/confio/weave` fails because of a missing dependency:

```
$ go get github.com/confio/weave
package github.com/tendermint/go-wire/data: cannot find package "github.com/tendermint/go-wire/data" in any of:
	/home/simon/go1.10.2/src/github.com/tendermint/go-wire/data (from $GOROOT)
	/home/simon/go/src/github.com/tendermint/go-wire/data (from $GOPATH)
```

It seems like https://github.com/tendermint/go-wire is not a thing anymore

**Comment by ruseinov** [comment]
This has been listed as a breaking change in TM 0.18 or 0.19, don't remember exactly.

**Comment by ruseinov** [comment]
@ethanfrey FYI this is what I was referring to when saying, that vendored deps are best kept in the repo :)

**Comment by ethanfrey** [comment]
You have to install with dep.

Make install 

It is in the readme. 

Ideally go get would work, but if you have used any of the tendermint deps, they all seem to have random breaking changes and push Master branches that are incompatible. 

I depped an old version that was stable. It is far from trivial to update all this

**Comment by ruseinov** [comment]
@ethanfrey dep won't work, they removed the repo.

**Comment by ethanfrey** [comment]
Point taken about keeping all deps committed in the repo

**Comment by webmaster128** [comment]
Now that we have the commit-vendor branch, is there a way to `go get` that branch? Internet says no on the first glance. I also tried to checkout the branch locally and go get from a local path but go says _unrecognized import path "/home/me/Downloads/weave" (import path does not begin with hostname)_.

Is there any other trick than copying that branch on a fork's master?

**Comment by ruseinov** [comment]
You don't need any tricks. Just git clone it into a proper gopath (same as you had master go get in). Or even just git pull in there and git checkout the branch.

**Comment by webmaster128** [comment]
That's a nice trick, thanks :)

**Comment by ruseinov** [comment]
@webmaster128 The way gopath works is: $GOPATH/src/repo_hostname/path/path... 
So basically when you need to go get something from github it's gonna be mkdir -p $GOPATH/src/github.com/user && cd $GOPATH/src/github.com/user  and git clone github.com/user/repo . Of course it is easier to go get master first and then checkout the branch.

**Comment by ruseinov** [comment]
@ethanfrey I think with new deps it should be all good now, shall we close this?

**Comment by ethanfrey** [comment]
:+1:
