### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by lapd-viosoft** [confio/weave#86]
Hello,
I'm trying basecoin (https://github.com/tendermint/basecoin/blob/master/docs/guide/basecoin-basics.md) and weave, it seems basecoin is old. However, basecoin support Multiple outputs, it can be used to send many different types of tokens between many different accounts at once in an atomic transaction.
Can you please tell me how to use weave(mycoind app) to send to multiple different account in one transaction?
Thank you!

**Comment by ruseinov** [comment]
@lapd-viosoft Hello,

Mycoind and weave currently don't support this and there are no plans for the near future.
However, you can take a look at https://github.com/iov-one/bcp-demo which is based on weave and has some extensions that might be of use for this scenario.

**Comment by lapd-viosoft** [comment]
Thank you!
